name: Android CI - Klotlin CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get keystore file
      run: 'echo "${{ secrets.ANDROID_RELEASE_STORE_FILE }}" | base64 -d > jdfossapps.keystore'
    - name: List files
      run: 'ls -d *'
    - name: MD5 checksum
      run: md5sum jdfossapps.keystore
    - name: Create Gradle Wrapper
      run: gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    # #Generates a zip with all the builds
    - uses: actions/upload-artifact@v2
      name: Generating APKs
      if: "contains(github.event.head_commit.message, 'gen apk')" #APKs generation trigger 
      with:
        name: builds
        path: |
          ~/**/*.apk
        #path: '~/**/*.apk'
        #~/**/app-debug.apk
        #~/**/lint-results.html
